[package]
name = "deaf"
version = "0.1.0"
edition = "2021"

[dependencies]
enumflags2 = "0.7.5"
num_enum = "0.5.9"
paste = "1.0.11"
thiserror = "1.0.38"

[dev-dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"