name: Docs

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Merge
        run: |
          git checkout documentation
          git merge master
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: documentation
      # - name: Build
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: doc
      #     args: --no-deps
      # - name: Configure
      #   run: |
      #     echo "<meta http-equiv=\"refresh\" content=\"0; url=deaf/index.html\">" > target/doc/index.html
      #     cp -r target/doc ./docs
