name: Docs

on:
  push:
    branches: [ documentation ]

jobs:
  test:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps
      - name: Configure
        run: |
          echo "<meta http-equiv=\"refresh\" content=\"0; url=deaf/index.html\">" > target/doc/index.html
          cp -r target/doc ./docs
