name: Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Documentation
        run: |
          cargo doc --all --no-deps
      - name: Configure Documentation
        run: |
          echo "<meta http-equiv=\"refresh\" content=\"0; url=deaf/index.html\">" > target/doc/index.html
          cp -r target/doc ./docs
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PIPELINE_TOKEN }}
          publish_branch: documentation
          publish_dir: ./docs
          keep_files: false
