name: Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: katyo/publish-crates@v2
        with:
          dry-run: true
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}